# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
commands:
  scanner:
    parameters:
      app:
        type: string
        description: "Github repo"
    steps:
    - run:
        name: Install Sonarqube scanner
        command: |

          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
          unzip sonar-scanner-cli-3.2.0.1227-linux.zip

    - run:
        name: Run Sonarqube scanner
        command:

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "presentation/build.gradle" }}
      - run:
          name: SonarCloud
          command: ./gradlew sonarqube -Dsonar.sources=~ -Dsonar.projectKey=leflix -Dsonar.organization=leflix -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=734bd3908550b86b1b836771f64bf05892e9731b

